server:
    port: 8001
eureka:
    instance:
        prefer-ip-address: true
        hostname: localhost
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://fulln:fulln@eureka-slave:8002/eureka/
spring:
    application:
        name: eurekaMaster
    security:
        user:
            name: fulln
            password: fulln

