server:
    port: 8001
eureka:
    instance:
        hostname: 192.168.0.108
    client:
        fetch-registry: false
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://fulln:fulln@${eureka.instance.hostname}:8002/eureka/
spring:
    application:
        name: eurekaMaster
    security:
        user:
            name: fulln
            password: fulln

