logging:
    path: logs/service
management:
    endpoint:
        shutdown:
            enabled: true
mapper:
    identity: MYSQL
    mappers: com.fulln.me.config.basic.MyMapper
    not-empty: false
mybatis:
    configuration:
        default-fetch-size: 100
        default-statement-timeout: 30
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*/*Mapper.xml
    type-aliases-package: me.fulln.base.model
    type-handlers-package: com.fulln.me.config.handle
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
server:
    port: 8080
    servlet:
        context-path: /service
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: just4p1aygam3@gmail.com
        password: qq1203943228
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
                    starttls:
                        enable: true
    jpa:
        show-sql: true
    messages:
        basename: Language.messages
    redis:
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
    profiles:
        active: dev




