com:
    fulln:
        api:
            defaultDownFile: /opt/source/_posts
            mail:
                send-adder: 245193247@qq.com
                password:
logging:
    file: /opt/logs/spring-boot-logging.log
    level:
        com:
            fulln:
                api:
                    dao: info
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/api?useSSL=false
        password: 123456
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 20
            max-lifetime: 1800000
            connection-test-query: SELECT 1
            connection-timeout: 30000
    redis:
        host: localhost
        password:
        port: 6379
        timeout: 5000
#    data:
#        elasticsearch:
#            cluster-nodes: 192.168.246.138:9300