com:
    fulln:
        api:
            defaultDownFile: D:/so/md
            mail:
                send-adder: 245193247@qq.com
                password:
logging:
    file: logs/service/spring-boot-logging.log
    level:
        com:
            fulln:
                api:
                    dao: info
spring:
    redis:
        host: localhost
        password:
        port: 6379
        timeout: 5000
# elasticsearch
    data:
        elasticsearch:
            cluster-nodes: 192.168.246.138:9300
            properties:
                path:
                    logs: ./elasticsearch/log #elasticsearch日志存储目录
                    data: ./elasticsearch/data #elasticsearch数据存储目录
            repositories:
                enabled: true
#        mongodb:
#            host: localhost
#            port: 27017
#            database: test

