com:
    fulln:
        api:
            urls:
                loginUrl: /login
                logoutUrl: /logout
                successUrl: /view
                unauthorizedUrl: /403
                nonBlockingUrl:
                    # 获取图片验证码
                    - /code
                    - /registered
                    # 首页
                    - /
                    # 项目性能监控模块
                    - /actuator/**
                    - /druid/**
                    # swaggerUi
                    - /static/**
                    - /webjars/**
                    - /swagger/**
                    - /swagger-resources/**
                    - /swagger-ui.html/**
                    - /v2/**
                    # 静态文件
                    - /css/**
                    - /font/**
                    - /img/**
                    - /js/**
            defaulthead:
                userName: fulln
                token: 6nKifRTHVYIZf5p+rFdGNg==
                sessionOutTime: 86400
            mail:
                account: 245193247
                host: smtp.qq.com
                is-auth: true
                img-path: ''
                out-time: 25000
logging:
    path: CONSOLE,debug,FILE
management:
    endpoint:
        shutdown:
            enabled: true
server:
    port: 8082
    servlet:
        context-path: /web
spring:
    messages:
        basename: Language.messages
    redis:
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
    thymeleaf:
        cache: false
        mode: HTML
        prefix: classpath:/templates/page/
    profiles:
        active: dev
    main:
        allow-bean-definition-overriding: true
feign:
    url: server
    path: /service
    httpclient:
        enabled: true
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
