version: '3'
services:
  eureka-master:
    build:
      context: ../
      dockerfile: eureka/Dockerfile
    container_name: eureka-master
    networks:
      - net-spring-db
    ports:
      - 8001:8001
  eureka-slaver:
    build:
      context: ../
      dockerfile: eurekaSlave/Dockerfile
    container_name: eureka-slaver
    ports:
      - 8002:8002
    networks:
      - net-spring-db
  config:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: config_local
    volumes:
      - ../config/src/main/resources/config:/opt/config
    ports:
      - 7000:7000
    networks:
      - net-spring-db
    depends_on:
      - eureka-master
      - eureka-slaver
networks:
  net-spring-db: