version: '3'
services:
  eureka-master:
    build:
      context: ../
      dockerfile: eureka/Dockerfile
    container_name: eureka-master
    networks:
      - net-spring-db
    ports:
      - 8001:8001
  eureka-slaver:
    build:
      context: ../
      dockerfile: eurekaSlave/Dockerfile
    container_name: eureka-slaver
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
    ports:
      - 8002:8002
    networks:
      - net-spring-db
  config:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: config_local
    volumes:
      - /Users/fulln/IdeaProjects/apiCloud/common/config/src/main/resources/config:/opt/config
    ports:
      - 7001:7000
    networks:
      - net-spring-db
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
    depends_on:
      - eureka-master
      - eureka-slaver
networks:
  net-spring-db: