server:
    port: 7000
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
             defaultZone: http://fulln:fulln@eureka-slaver:8002/eureka/, http://fulln:fulln@eureka-master:8001/eureka/
spring:
    security:
        user:
            name: fulln
            password: fulln
    application:
        name: configServer
    cloud:
        config:
            server:
                #本地化配置
                native:
                    search-locations: classpath:config/
                bootstrap: true