server:
    port: 7000
eureka:
    instance:
        hostname: 192.168.0.108
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
             defaultZone: http://fulln:fulln@eureka-slave:8002/eureka/, http://fulln:fulln@eureka-master:8001/eureka/
spring:
    security:
        user:
            name: fulln
            password: fulln
    application:
        name: configServer
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/fulln/config/
                    search-paths: springCloud/config
                    password:
                    username:

