server:
    port: 7001
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
             defaultZone: http://fulln:fulln@localhost:8002/eureka/, http://fulln:fulln@localhost:8001/eureka/
spring:
    profiles:
        #本地化配置必须开启这个配置
        active: native
    security:
        user:
            name: fulln
            password: fulln
    application:
        name: configServer
    cloud:
        config:
            server:
                #本地化配置
                native:
                    search-locations: classpath:/config
