server:
  port: 7000
eureka:
  client:
#    fetch-registry: true
    serviceUrl:
      defaultZone: http://fulln:fulln@localhost:8000/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github:com/fulln/config.git
          search-paths: springCloud/config
          password: 
          username: 
